load("//lilypond:build.bzl", "ly_png", "ly_png_midi")

ly_png_midi(name="camp_barton_song", src="camp_barton_song.ly")
ly_png_midi(name="dummy_line", src="dummy_line.ly")
ly_png_midi(name="dunderbeck", src="dunderbeck.ly")
ly_png_midi(name="mountain_dew", src="mountain_dew.ly")
ly_png_midi(name="the_titanic", src="the_titanic.ly")
