load("@bazel_lilypond//:lilypond.bzl", "lilypond")

lilypond(name="camp_barton_song")
lilypond(name="dummy_line")
lilypond(name="dunderbeck")
lilypond(name="mountain_dew")
lilypond(name="quartermaster_store")
lilypond(name="the_titanic")
